### ISSUE TITLE
Teamcity build does not run tests

### ISSUE THREAD

**Issue by tomalec** [Starcounter/UniformDocs#361]
### Steps to reproduce
1. Commit to a branch,
2. Push changes,
3. Check TC log, like https://teamcity.starcounter.org/viewLog.html?buildId=65382&buildTypeId=Apps_UniformDocs_UniformDocsMaster24branchWithStarcounterDevelopNightly&tab=buildLog

### Expected result
Test should run

### Actual result
No tests results are visible.

### Technical information

Tests are run and reported when build for client-side libraries, like https://teamcity.starcounter.org/viewLog.html?buildId=64843&buildTypeId=Apps_WebPlatform_ImportedTemplate_TestWithApps
and seems to be failing for some time already

**Comment by tomalec** [comment]
//cc @warpech @ubbeK

**Comment by warpech** [comment]
I think it runs the tests in https://teamcity.starcounter.org/project.html?projectId=Apps_WebPlatform but does not report to GitHub, see:

<img width="1499" alt="screen shot 2018-09-21 at 13 38 39" src="https://user-images.githubusercontent.com/566463/45879145-acba2780-bda3-11e8-968f-b4cffc9eab00.png">

**Comment by tomalec** [comment]
But the point is about UniformDocs changes, not SCF like those: https://github.com/Starcounter/UniformDocs/commits/improve-flaky-dropdown-tests

https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_UniformDocs_UniformDocsMaster24branchWithStarcounterDevelopNightly&branch_Apps_UniformDocs=improve-flaky-dropdown-tests&tab=buildTypeStatusDiv

**Comment by warpech** [comment]
Sorry, I messed up two problems. I have moved the problem that I described into a new issue: https://github.com/Starcounter/StarcounterClientFiles/issues/121

The problem in this issue is about not found PowerShell script. @ubbeK can you pls take a look?

https://teamcity.starcounter.org/viewLog.html?buildId=65382&buildTypeId=Apps_UniformDocs_UniformDocsMaster24branchWithStarcounterDevelopNightly&tab=buildLog

<img width="1499" alt="screen shot 2018-09-21 at 13 51 55" src="https://user-images.githubusercontent.com/566463/45879678-aa58cd00-bda5-11e8-8365-2c36bc5bbac7.png">

**Comment by warpech** [comment]
I know the problem. I will fix it. We use the word `KitchenSink` in a file path in the TC config.

**Comment by warpech** [comment]
@tomalec I've fixed that... Now we can see failing tests on `master`. Hooray (?) ;)

**Comment by tomalec** [comment]
Great, thanks!

**Comment by ubbeK** [comment]
Yay, I didn't need to lift a finger, except writing this message =P
